name: widescape
favicon: null
layout_spectrum: 0.4691332154907286
typography_spectrum: 0.6528799431398511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.16697707632556558
  lightness: 0.35146667063236237
  saturation: 0.19635889795608819
  rhythmicContrast: 0.0033382540568709373
purpose: []
